apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "salon-booking-chart.fullname" . }}-frontend

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: salon-frontend

  template:
    metadata:
      labels:
        app: salon-frontend

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          ports:
            - containerPort: {{ .Values.frontend.container.port }}