name: Deploy Cloud-Native Salon Booking Platform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Display repository contents
        run: |
          pwd
          ls -la

      - name: Display tool versions
        run: |
          git --version
          docker --version

      - name: Build backend Docker image
        run: |
          docker build -t salon-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t salon-frontend:latest ./frontend

      - name: Tag backend image
        run: |
          docker tag salon-backend:latest 825765402564.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-salon-booking-platform-backend:latest

      - name: Tag frontend image
        run: |
          docker tag salon-frontend:latest 825765402564.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-salon-booking-platform-frontend:latest

      - name: Push backend image
        run: |
          docker push 825765402564.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-salon-booking-platform-backend:latest

      - name: Push frontend image
        run: |
          docker push 825765402564.dkr.ecr.eu-west-1.amazonaws.com/cloud-native-salon-booking-platform-frontend:latest

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ${{ secrets.EC2_PATH }}

            git pull origin main

            helm upgrade --install salon-booking ./salon-booking-chart \
               --set image.tag=latest \
               --set frontend.image.tag=latest