name: Deploy Cloud-Native Salon Booking Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display repository contents
        run: |
          pwd
          ls -la